[wnn_demo]
raw_data_dirs = [
    # wnn
    "data/raw/rna+adt/wnn/p1_0",
    "data/raw/rna+adt/wnn/p2_0",
    "data/raw/rna+adt/wnn/p3_0",
]
raw_data_frags = [
    "",
    "",
    "",
]
combs = [
    # dogma
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
]
comb_ratios = [
    # dogma
    [ 1 ], [ 1 ], [ 1 ]
]

[dogma_demo]
raw_data_dirs = [
    # dogma
    "data/raw/atac+rna+adt/dogma/lll_ctrl",
    "data/raw/atac+rna+adt/dogma/lll_stim",
    "data/raw/atac+rna+adt/dogma/dig_ctrl",
]
raw_data_frags = [
    # dogma
    "GSM5065524_LLL_CTRL_fragments.tsv.gz",
    "GSM5065527_LLL_STIM_fragments.tsv.gz",
    "GSM5065530_DIG_CTRL_fragments.tsv.gz"
]
combs = [
    # dogma
    [ ["atac", "rna", "adt"] ],
    [ ["atac", "rna", "adt"] ],
    [ ["atac", "rna", "adt"] ],
]
comb_ratios = [
    # dogma
    [ 1 ], [ 1 ], [ 1 ]
]


[dogma_demo_reciprocal]
raw_data_dirs = [
    # dogma
    "data/raw/atac+rna+adt/dogma/dig_stim",
]
raw_data_frags = [
    # dogma
    "GSM5065533_DIG_STIM_fragments.tsv.gz"]
combs = [
    # dogma
    [ ["atac", "rna", "adt"] ],
]
comb_ratios = [
    # dogma
    [ 1 ]
]